apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQVBvMkwweXZPWDIydnVQNnZJbzJjYUF3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa016SXhaVE5oWVdNdE9UbGlaUzAwTVdWakxXRXpZVFl0TkRVM01UUmtabUkyTnpreApNQ0FYRFRJek1UQXhPVEU0TXpNMU1sb1lEekl3TlRNeE1ERXhNVGt6TXpVeVdqQXZNUzB3S3dZRFZRUURFeVF6Ck1qRmxNMkZoWXkwNU9XSmxMVFF4WldNdFlUTmhOaTAwTlRjeE5HUm1ZalkzT1RFd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDdFVvcVhZdnE1MjVLdW1LYzRtZEs1TGdWWHoyU3k4ZjlldHdWeQp3dStzdGxuN2k0OU9BVGoraVg2NDZEdUIyb0hQeHNqQWoySjhTVnNKZ3E5SDY4cUVUcTI0Zmt2SytWZkc3THE0CnpjTis5QmtMWFhwNDdOaUJ4cmNmTUtoWVpVWUtRcGxYWDBaeXVja2dieVVPWHRqc1V2cStEN0R5UEtXRTl3NU8KT3ZVR0czUzZ6UzFySFZRWVplci95Q215dC9Bbk5Xd2MwcjgyWmJFQStpV0FsV01BNEJzK01tMWVkeU1ienZmdgpjMW4wTmFwWmowT0Nsd083ZUQ3MUg0V1owR25YaDZnQlhDcUlvK3Z1eU9uN0RXaUwzdjVYaFRieVQyTTM4UWt0CnZ6V2NzU3FZc0w5UGpMUG96VlZrRU45b3FmWStKaWZheWtndTl0TFh5UHpld0NyWTZmRkJqeTlySVdaQyt4ZFYKWmw5MjNQZWNpOENUaTB6bHRxbjJOSGtCdFRPQ3lSdjQvWU5WRzhFekVvMm5Xbk1iMlVwTWVhU1FJU3FuRUh4TwppWVpzb3l0OE9hN2JmVUpjQVRLRHV6VnVLZnNWdWxDSlhSRjNtMk1SZWNtZkhVYitaWE52ZFFwRU0yOFlsM05RCnMwM3A3VUtsNUdEekUzUVJzN2xRaVljS2taY0NBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTS9LcEZDdWhyWjNUQWtRSFNvU2pDSTEzMmdRTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQVk4akNLdTNiSGVvUTUyY1lPWVdsaDlHem1PNWxDcU5LaWVUbXhyY3o0CnNIeEVsOS90STNwUlJMUjlsQzlCRFpPSlM1RnNwZ2cwK3lxdXEranNWazZwelJPd2FaZ2l2bnlZVXM3ckZibGsKMXlicGgzaytkUWJLM3RGUlFWQjZ1ZWw0SFN3L3R6dWl4dXdBaE9ubGZ5M1Nqcm5EU3lpNERVRXAyZWljemJTZAprVUdMWW1OdVJ2NzEwQVYzanRUc0svQXB0S3RNUlNPZHBHdkxMTUUvRmJwMHJIQTF3Z0hDN1JyMUs4NWRBWlg0CmNicWViSHRxYUxkb1hEd1RyL2pydW5NZlhUcllPeHVrRC90L0tEemFjL1kwRzBVclVYdFNaL3A2ZExBbFE2WTMKcTlRWmtEb3NsR2hRbkNSSjgwY3JNYlR1ekFITjFGa0xxR2U3OGlrWStOWHVxdmJZb1cwVTNQRlVzUDcwRjcrZwp2ZXZnNTlMOGR4OWlDMVlmbjNkck9OeW1jSlM2SWUwZ2tZWHlmSzZwVWM2RUFnY0JrSTk0NmRmbkNoMEVMVlZSCnJmWFJZdzdtbXlnT1p2R1pUUTkwYUhZNWgvT1RXMllMbUdydEJ0elJLbTJmbDIxQXZ0SVpadEtVK25pOTFrdUMKRDVYU2ZUYlFJZENXTjA3Zk1taldwbnM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.170.31.202
  name: gke_arryved-staging_us-central1_gke-yvqu

contexts:
- context:
    cluster: gke_arryved-staging_us-central1_gke-yvqu
    user: gke_arryved-staging_us-central1_gke-yvqu
  name: gke_arryved-staging_us-central1_gke-yvqu

current-context: gke_arryved-staging_us-central1_gke-yvqu

preferences: {}

users:
- name: gke_arryved-staging_us-central1_gke-yvqu
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args: null
      command: gke-gcloud-auth-plugin
      env: null
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/blog/products/containers-kubernetes/kubectl-auth-changes-in-gke
      interactiveMode: IfAvailable
      provideClusterInfo: true
