# This config is used for testing; keep real config in ansible
---
logLevel: info
readTimeoutS: 5
writeTimeoutS: 10

tls:
  ciphers:
    - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    - TLS_RSA_WITH_AES_128_CBC_SHA
    - TLS_RSA_WITH_AES_256_CBC_SHA
  minVersion: "1.2"

topology:
  dev:
  prod:
    clusters:
      arryved-api:
        hosts:
          arryved-api0.prod.arryved.com:
          arryved-api1.prod.arryved.com:
          arryved-api2.prod.arryved.com:
          arryved-api3.prod.arryved.com:
          arryved-api4.prod.arryved.com:
          canary-api.prod.arryved.com:
            canary: true
          canary-api1.prod.arryved.com:
            canary: true
  sandbox:
  staging:
